name: Validate

on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build dependencies with Maven
        run: mvn clean validate -Pbootstrap --no-transfer-progress
      
      - name: SCA with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify -Pvalidate --no-transfer-progress
